import Head from 'next/head'
import Article from '@components/article'
import { getFilesInDirectory } from '../logic/fileSystem'
import { getHtmlFromMarkdown } from '../logic/getHtmlFromMarkdown'
import matter from 'gray-matter';
import { remark } from 'remark';
import html from 'remark-html';

import '@styles/article.css'

const myArticle = {
  title: "My First Article",
  name: "Colin Teahan",
  date: new Date(),
  children: "This is my first article!"
}

export default async function Home() {

  const file = await getFilesInDirectory('docs')
  const html = await getHtmlFromMarkdown(file[1].content)

  return (
    <>
      <Head>
        <title>Asleepace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="article">
          <article>
            <div dangerouslySetInnerHTML={{ __html: html }} />
          </article>
          <div className="article-side">
            <h3>On this page</h3>
          </div>
        </div>
    </>
  )
}
