import Head from 'next/head'
import { getFilesInDirectory } from '../logic/fileSystem'
import { getHtmlFromMarkdown } from '../logic/getHtmlFromMarkdown'


import '@styles/article.css'

const myArticle = {
  title: "My First Article",
  name: "Colin Teahan",
  date: new Date(),
  children: "This is my first article!"
}

export default async function Home() {

  const file = await getFilesInDirectory('docs')
  const html = await getHtmlFromMarkdown(file[1].content)
  console.log(html.match(/<h2>(.*)<\/h2>/g))

  return (
    <>
      <Head>
        <title>Asleepace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="article">
          <article>
            <div dangerouslySetInnerHTML={{ __html: html }} />
          </article>
        </div>
    </>
  )
}
