name: Deploy
on:
  pull_request:
    types: [labeled]
jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    if: github.event.label.name == 'deploy'
    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      - name: Run deploy script
        run: ssh staging '~/asleepace.com/scripts/deploy.sh'

      - name: Success Notification
        if: success()
        run: |
          curl -X POST "https://asleepace.com/api/notify" \
            -H "Content-Type: application/json" \
            -d '{"type": "deploy", "message": "Deploy successful!", "commit": "${{ github.sha }}"}'
